### PROJECT CONFIG ###
BUGONE_PATH=../..
BOARD=bugone_mini

PRG=sht21
DEVICE_FILES=led.o sht2x.o twi.o bandgap.o battery.o random.o
FILES=main.o

include $(BUGONE_PATH)/projects/bugone.inc

$(BOARD)/main.o:main.c

