### PROJECT CONFIG ###
BUGONE_PATH=../..
BOARD=bugone

PRG=main
NO_RFM12=1
FILES=main.o rfm12.o bugOne.o config.o apps.o network.o get.o ping.o value.o led.o
DEVICE_FILES=led.o


include $(BUGONE_PATH)/projects/bugone.inc

$(BOARD)/main.o:main.c
