### PROJECT CONFIG ###
BUGONE_PATH=../..
BOARD=bugone

PRG=test
# DISABLE_CORE=1
DISABLE_MAIN=1
FILES=main.o

DEVICE_FILES=led.o bandgap.o const.o

include $(BUGONE_PATH)/projects/bugone.inc

$(BOARD)/main.o:main.c
