### PROJECT CONFIG ###
BUGONE_PATH=../..
BOARD=bugone

PRG=test
NO_RFM12=1
FILES=main.o rfm12.o bugOne.o led.o network.o config.o get.o value.o ping.o apps.o bandgap.o const.o

DEVICE_FILES=led.o bandgap.o const.o

include $(BUGONE_PATH)/projects/bugone.inc

$(BOARD)/main.o:main.c
