### PROJECT CONFIG ###
BUGONE_PATH=../..
BOARD=bugone

PRG=shield1
DEVICE_FILES=const.o led.o dht11.o photoresistor.o bandgap.o
FILES=main.o

include $(BUGONE_PATH)/projects/bugone.inc

$(BOARD)/main.o:main.c


